FROM nvcr.io/nvidia/pytorch:23.10-py3

RUN apt-get update && apt-get install git ca-certificates ffmpeg libsm6 libxext6  -y
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY setup.py .
COPY src src
RUN pip install -e .

RUN pip install opencv-fixer==0.2.5
RUN python -c "from opencv_fixer import AutoFix; AutoFix()"